# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0002_auto_20160818_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='books',
            name='review',
        ),
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beltreview.Books'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beltreview.Users'),
        ),
    ]
